//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncryptionStudy {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Tests {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tests() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EncryptionStudy.Tests", typeof(Tests).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на a) 3.
        /// </summary>
        internal static string Answer1_1 {
            get {
                return ResourceManager.GetString("Answer1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на b) 2.
        /// </summary>
        internal static string Answer1_2 {
            get {
                return ResourceManager.GetString("Answer1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на c) 4.
        /// </summary>
        internal static string Answer1_3 {
            get {
                return ResourceManager.GetString("Answer1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на a) Independent blocks encryption.
        /// </summary>
        internal static string Answer10_1 {
            get {
                return ResourceManager.GetString("Answer10_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на b)  Encryption, dependent on the previous blocks.
        /// </summary>
        internal static string Answer10_2 {
            get {
                return ResourceManager.GetString("Answer10_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на c) Whole block completion.
        /// </summary>
        internal static string Answer10_3 {
            get {
                return ResourceManager.GetString("Answer10_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на a) A recipient will not be able to find the end of useful data.
        /// </summary>
        internal static string Answer11_1 {
            get {
                return ResourceManager.GetString("Answer11_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на b) There is a risk of information leak.
        /// </summary>
        internal static string Answer11_2 {
            get {
                return ResourceManager.GetString("Answer11_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на c) There is no correct answer.
        /// </summary>
        internal static string Answer11_3 {
            get {
                return ResourceManager.GetString("Answer11_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на a) Substitution, permutation, XOR ciphers.
        /// </summary>
        internal static string Answer12_1 {
            get {
                return ResourceManager.GetString("Answer12_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на b) Symmetric, asymmetric and streamer ciphers.
        /// </summary>
        internal static string Answer12_2 {
            get {
                return ResourceManager.GetString("Answer12_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на c) Substitution and permutation ciphers.
        /// </summary>
        internal static string Answer12_3 {
            get {
                return ResourceManager.GetString("Answer12_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на a) A method of cryptographic conversion, which lies in a swap of initial text symbols according to a certain rule.
        /// </summary>
        internal static string Answer13_1 {
            get {
                return ResourceManager.GetString("Answer13_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на b) A system of block substitution.
        /// </summary>
        internal static string Answer13_2 {
            get {
                return ResourceManager.GetString("Answer13_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на c) A method of conversion, which lies in a substitution of initial text symbols to another ones..
        /// </summary>
        internal static string Answer13_3 {
            get {
                return ResourceManager.GetString("Answer13_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на a) XOR cipher.
        /// </summary>
        internal static string Answer14_1 {
            get {
                return ResourceManager.GetString("Answer14_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на b) Streamer cipher.
        /// </summary>
        internal static string Answer14_2 {
            get {
                return ResourceManager.GetString("Answer14_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на c) Substitution cipher.
        /// </summary>
        internal static string Answer14_3 {
            get {
                return ResourceManager.GetString("Answer14_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на a) Block encryption.
        /// </summary>
        internal static string Answer15_1 {
            get {
                return ResourceManager.GetString("Answer15_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на b) Streamer encryption.
        /// </summary>
        internal static string Answer15_2 {
            get {
                return ResourceManager.GetString("Answer15_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на c) To the both types of encryption.
        /// </summary>
        internal static string Answer15_3 {
            get {
                return ResourceManager.GetString("Answer15_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на a) A symmetric algorithm works slower than an asymmetric one.
        /// </summary>
        internal static string Answer16_1 {
            get {
                return ResourceManager.GetString("Answer16_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на b) An asymmetric algorithm works slower than a symmetric one.
        /// </summary>
        internal static string Answer16_2 {
            get {
                return ResourceManager.GetString("Answer16_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на c) Both algorithms require lots of computational resources.
        /// </summary>
        internal static string Answer16_3 {
            get {
                return ResourceManager.GetString("Answer16_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на a) 3.
        /// </summary>
        internal static string Answer17_1 {
            get {
                return ResourceManager.GetString("Answer17_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на b) 2.
        /// </summary>
        internal static string Answer17_2 {
            get {
                return ResourceManager.GetString("Answer17_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на c) 4.
        /// </summary>
        internal static string Answer17_3 {
            get {
                return ResourceManager.GetString("Answer17_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на a) The same cryptographic strength as the strongest cipher it uses.
        /// </summary>
        internal static string Answer18_1 {
            get {
                return ResourceManager.GetString("Answer18_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на b) The same cryptographic strength as the weakest cipher it uses.
        /// </summary>
        internal static string Answer18_2 {
            get {
                return ResourceManager.GetString("Answer18_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на c) Cryptographic strength depends on all the ciphers used.
        /// </summary>
        internal static string Answer18_3 {
            get {
                return ResourceManager.GetString("Answer18_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на a) Secret information, used by a cryptographic algorithm while encrypting/ decrypting of the message.
        /// </summary>
        internal static string Answer19_1 {
            get {
                return ResourceManager.GetString("Answer19_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на b) Randomly generated key of a symmetric cipher for a hybrid encryption.
        /// </summary>
        internal static string Answer19_2 {
            get {
                return ResourceManager.GetString("Answer19_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на c) There is no correct answer.
        /// </summary>
        internal static string Answer19_3 {
            get {
                return ResourceManager.GetString("Answer19_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на a)	measures to restrict access to information.
        /// </summary>
        internal static string Answer2_1 {
            get {
                return ResourceManager.GetString("Answer2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на b)	verification of authenticity and intactness of information.
        /// </summary>
        internal static string Answer2_2 {
            get {
                return ResourceManager.GetString("Answer2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на c)	 both variants are correct.
        /// </summary>
        internal static string Answer2_3 {
            get {
                return ResourceManager.GetString("Answer2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на a)A conversion, when symbols of an initial text are folded according to a module, which is equal in capacity with the alphabet, with symbols of pseudo-random sequence.
        /// </summary>
        internal static string Answer20_1 {
            get {
                return ResourceManager.GetString("Answer20_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на b) A XOR form, which converses an open text into encrypted one subsequently, bite by bite..
        /// </summary>
        internal static string Answer20_2 {
            get {
                return ResourceManager.GetString("Answer20_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на c) There is no correct answer.
        /// </summary>
        internal static string Answer20_3 {
            get {
                return ResourceManager.GetString("Answer20_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на a)	Cheapness.
        /// </summary>
        internal static string Answer3_1 {
            get {
                return ResourceManager.GetString("Answer3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на b)	A list of possible threats.
        /// </summary>
        internal static string Answer3_2 {
            get {
                return ResourceManager.GetString("Answer3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на c)	Necessity of protection.
        /// </summary>
        internal static string Answer3_3 {
            get {
                return ResourceManager.GetString("Answer3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на a)	A secret text for encryption/decryption of the message.
        /// </summary>
        internal static string Answer4_1 {
            get {
                return ResourceManager.GetString("Answer4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на b)	A secret formula for encryption/decryption of the message.
        /// </summary>
        internal static string Answer4_2 {
            get {
                return ResourceManager.GetString("Answer4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на c)	A secret information for encryption/decryption of the message.
        /// </summary>
        internal static string Answer4_3 {
            get {
                return ResourceManager.GetString("Answer4_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на a)	Symmetric has only one key, while asymmetric has 2 keys.
        /// </summary>
        internal static string Answer5_1 {
            get {
                return ResourceManager.GetString("Answer5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на b)	Symmetric has two keys, while asymmetric has one.
        /// </summary>
        internal static string Answer5_2 {
            get {
                return ResourceManager.GetString("Answer5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на c)	There are no differences.
        /// </summary>
        internal static string Answer5_3 {
            get {
                return ResourceManager.GetString("Answer5_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на a) Symmetric encryption.
        /// </summary>
        internal static string Answer6_1 {
            get {
                return ResourceManager.GetString("Answer6_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на b) Asymmetric encryption.
        /// </summary>
        internal static string Answer6_2 {
            get {
                return ResourceManager.GetString("Answer6_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на c) Both types of encryption.
        /// </summary>
        internal static string Answer6_3 {
            get {
                return ResourceManager.GetString("Answer6_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на a) A study of methods of detection of vulnerable places in an algorithm.
        /// </summary>
        internal static string Answer7_1 {
            get {
                return ResourceManager.GetString("Answer7_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на b) A study of methods of initial text detection.
        /// </summary>
        internal static string Answer7_2 {
            get {
                return ResourceManager.GetString("Answer7_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на c) Both variants are correct.
        /// </summary>
        internal static string Answer7_3 {
            get {
                return ResourceManager.GetString("Answer7_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на a) The text is divided only into 2 blocks.
        /// </summary>
        internal static string Answer8_1 {
            get {
                return ResourceManager.GetString("Answer8_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на b) The text is divided into a great amount of blocks of different length.
        /// </summary>
        internal static string Answer8_2 {
            get {
                return ResourceManager.GetString("Answer8_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на c) The text is divided into equal blocks.
        /// </summary>
        internal static string Answer8_3 {
            get {
                return ResourceManager.GetString("Answer8_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на a) Encryption is impossible.
        /// </summary>
        internal static string Answer9_1 {
            get {
                return ResourceManager.GetString("Answer9_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на b) Block is completed to the necessary length.
        /// </summary>
        internal static string Answer9_2 {
            get {
                return ResourceManager.GetString("Answer9_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на c) Unfilled block does not participate in encryption.
        /// </summary>
        internal static string Answer9_3 {
            get {
                return ResourceManager.GetString("Answer9_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на How many aspects of protection exist?.
        /// </summary>
        internal static string Question1 {
            get {
                return ResourceManager.GetString("Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In which of the methods the unfinished block is filled with zero ones and a single bite?.
        /// </summary>
        internal static string Question10 {
            get {
                return ResourceManager.GetString("Question10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.
        /// </summary>
        internal static string Question10Answer {
            get {
                return ResourceManager.GetString("Question10Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Why independent blocks encryption is not efficient when dealing with great amounts of information?.
        /// </summary>
        internal static string Question11 {
            get {
                return ResourceManager.GetString("Question11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.
        /// </summary>
        internal static string Question11Answer {
            get {
                return ResourceManager.GetString("Question11Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Block ciphers are divided into:.
        /// </summary>
        internal static string Question12 {
            get {
                return ResourceManager.GetString("Question12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0.
        /// </summary>
        internal static string Question12Answer {
            get {
                return ResourceManager.GetString("Question12Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Substitution cipher is –.
        /// </summary>
        internal static string Question13 {
            get {
                return ResourceManager.GetString("Question13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0.
        /// </summary>
        internal static string Question13Answer {
            get {
                return ResourceManager.GetString("Question13Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The simplest block cipher is-.
        /// </summary>
        internal static string Question14 {
            get {
                return ResourceManager.GetString("Question14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.
        /// </summary>
        internal static string Question14Answer {
            get {
                return ResourceManager.GetString("Question14Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на XOR is related to.
        /// </summary>
        internal static string Question15 {
            get {
                return ResourceManager.GetString("Question15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.
        /// </summary>
        internal static string Question15Answer {
            get {
                return ResourceManager.GetString("Question15Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mark the correct statement.
        /// </summary>
        internal static string Question16 {
            get {
                return ResourceManager.GetString("Question16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.
        /// </summary>
        internal static string Question16Answer {
            get {
                return ResourceManager.GetString("Question16Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The number of ways of block encryption is.
        /// </summary>
        internal static string Question17 {
            get {
                return ResourceManager.GetString("Question17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0.
        /// </summary>
        internal static string Question17Answer {
            get {
                return ResourceManager.GetString("Question17Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hybrid key has.
        /// </summary>
        internal static string Question18 {
            get {
                return ResourceManager.GetString("Question18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.
        /// </summary>
        internal static string Question18Answer {
            get {
                return ResourceManager.GetString("Question18Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Session key is-.
        /// </summary>
        internal static string Question19 {
            get {
                return ResourceManager.GetString("Question19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.
        /// </summary>
        internal static string Question19Answer {
            get {
                return ResourceManager.GetString("Question19Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0.
        /// </summary>
        internal static string Question1Answer {
            get {
                return ResourceManager.GetString("Question1Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The protection of information means-.
        /// </summary>
        internal static string Question2 {
            get {
                return ResourceManager.GetString("Question2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Permutation cipher is.
        /// </summary>
        internal static string Question20 {
            get {
                return ResourceManager.GetString("Question20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.
        /// </summary>
        internal static string Question20Answer {
            get {
                return ResourceManager.GetString("Question20Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.
        /// </summary>
        internal static string Question2Answer {
            get {
                return ResourceManager.GetString("Question2Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The principle of the second aspect of information security.
        /// </summary>
        internal static string Question3 {
            get {
                return ResourceManager.GetString("Question3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.
        /// </summary>
        internal static string Question3Answer {
            get {
                return ResourceManager.GetString("Question3Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A key is-.
        /// </summary>
        internal static string Question4 {
            get {
                return ResourceManager.GetString("Question4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.
        /// </summary>
        internal static string Question4Answer {
            get {
                return ResourceManager.GetString("Question4Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на What is the difference between a symmetric encryption and an asymmetric one?.
        /// </summary>
        internal static string Question5 {
            get {
                return ResourceManager.GetString("Question5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0.
        /// </summary>
        internal static string Question5Answer {
            get {
                return ResourceManager.GetString("Question5Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hybrid cipher uses:.
        /// </summary>
        internal static string Question6 {
            get {
                return ResourceManager.GetString("Question6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.
        /// </summary>
        internal static string Question6Answer {
            get {
                return ResourceManager.GetString("Question6Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cryptanalysis is-.
        /// </summary>
        internal static string Question7 {
            get {
                return ResourceManager.GetString("Question7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.
        /// </summary>
        internal static string Question7Answer {
            get {
                return ResourceManager.GetString("Question7Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The peculiarity of block encryption is-.
        /// </summary>
        internal static string Question8 {
            get {
                return ResourceManager.GetString("Question8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2.
        /// </summary>
        internal static string Question8Answer {
            get {
                return ResourceManager.GetString("Question8Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If the length of a message is less than the length of a block, then.
        /// </summary>
        internal static string Question9 {
            get {
                return ResourceManager.GetString("Question9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1.
        /// </summary>
        internal static string Question9Answer {
            get {
                return ResourceManager.GetString("Question9Answer", resourceCulture);
            }
        }
    }
}
